namespace: scenario
replicaCount: 1

egressnode:
  name: egressnode
  image: jorgealmansa/p4-imagen:encrypted-pandora2
  runtimeClassName: kata-qemu-tdx
  runtimeHandler: kata-qemu-tdx
  privileged: true
  command:
    - "/bin/sh"
    - "-c"
    - |
      sudo chmod +x /home/p4/pot/docker/run.sh
      sudo /home/p4/pot/docker/run.sh 14
  networks:
    - name: cluster-network
      interface: net1
      ips:
        - "10.0.3.2/24"
      mac: "02:42:0a:00:03:02"
    - name: egress-cluster-h2
      interface: net2
      ips:
        - "10.1.2.2/24"
      mac: "02:42:0a:01:02:02"
    - name: cluster-controller
      interface: net3
      ips:
        - "10.0.0.14/24"
      mac: "02:42:0a:00:00:0e"
  volumeMounts:
    - name: pot-volume
      mountPath: /home/p4/pot
    - name: pot-run-config
      mountPath: /home/p4/pot/docker/run.sh
      subPath: run.sh
  volumes:
    - name: pot-volume
      hostPath:
        path: /home/mw/PoT_PRIVATEER/keys
        type: Directory
    - name: pot-run-config
      configMap:
        name: pot-run-config
        defaultMode: 0755
