apiVersion: v1
kind: Pod
metadata:
  name: controller
  namespace: scenario
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "cluster-controller",
          "interface": "net1",
          "ips": [ "10.0.0.10/24" ],
          "mac": "02:42:0a:00:00:0a"
        }
      ]
spec:
  containers:
  - name: controller
    image: jorgealmansa/p4custom-kafka:latest
    securityContext:
      privileged: true
    command:
      - /bin/sh
      - -c
      - |
        sudo sysctl -w net.ipv4.ip_forward=1
        sudo arp -s 10.0.0.11 02:42:0a:00:00:0b
        chmod +x /home/p4/pot/docker/run.sh
        /home/p4/pot/docker/run.sh controller-tfs 4
    volumeMounts:
    - mountPath: /home/p4/pot
      name: pot-volume
      readOnly: false
    - mountPath: /home/p4/pot/docker/run.sh
      name: pot-run-config
      subPath: run.sh
      readOnly: false

  volumes:
      - name: pot-volume
        hostPath:
          path: /home/ubuntu/PoT/PoT_PRIVATEER
          type: Directory
      - name: pot-run-config
        configMap:
          name: pot-run-config
          defaultMode: 0755
