apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: static-net
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br0",
    "ipam": {
      "type": "host-local",
      "subnet": "10.0.0.0/24",
      "rangeStart": "10.0.0.10",
      "rangeEnd": "10.0.0.250",
      "gateway": "10.0.0.1"
    }
  }'
