# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpcService.proto\x12\x0esrc.main.proto\"\xa0\x01\n\rupdateRequest\x12\x17\n\x0f\x61\x64\x64ressFamilyID\x18\x01 \x01(\t\x12\x0f\n\x07nextHop\x18\x02 \x01(\t\x12\x15\n\rasPathSegment\x18\x03 \x01(\t\x12&\n\x04node\x18\x04 \x03(\x0b\x32\x18.src.main.proto.nodeInfo\x12&\n\x04link\x18\x05 \x03(\x0b\x32\x18.src.main.proto.linkInfo\"^\n\x08nodeInfo\x12\x10\n\x08nodeName\x18\x01 \x01(\t\x12\r\n\x05igpID\x18\x02 \x01(\t\x12\x0f\n\x07\x62gplsID\x18\x03 \x01(\t\x12\x0c\n\x04\x61sID\x18\x04 \x01(\x05\x12\x12\n\nlearntFrom\x18\x05 \x01(\t\"\x8a\x03\n\x08linkInfo\x12\x10\n\x08remoteID\x18\x01 \x01(\t\x12\x0f\n\x07localID\x18\x02 \x01(\t\x12\x14\n\x0cremoteIPv4ID\x18\x03 \x01(\t\x12\x13\n\x0blocalIPv4ID\x18\x04 \x01(\t\x12.\n\x05local\x18\x05 \x01(\x0b\x32\x1f.src.main.proto.NodeDescriptors\x12/\n\x06remote\x18\x06 \x01(\x0b\x32\x1f.src.main.proto.NodeDescriptors\x12\x13\n\x0b\x61vailableBw\x18\x07 \x01(\x02\x12\x12\n\nresidualBw\x18\x08 \x01(\x02\x12\x10\n\x08utilized\x18\t \x01(\x02\x12\x14\n\x0cmaxLinkDelay\x18\n \x01(\x02\x12\x14\n\x0cminLinkDelay\x18\x0b \x01(\x02\x12\x16\n\x0e\x64\x65layVariation\x18\x0c \x01(\x02\x12\r\n\x05\x64\x65lay\x18\r \x01(\x02\x12\x17\n\x0fTEDefaultMetric\x18\x0e \x01(\x05\x12\x14\n\x0c\x61\x64jacencySid\x18\x0f \x01(\t\x12\x12\n\nlearntFrom\x18\x10 \x01(\t\"4\n\x0fNodeDescriptors\x12\x10\n\x08\x61sNumber\x18\x01 \x01(\t\x12\x0f\n\x07\x62gplsID\x18\x02 \x01(\t\"\x1d\n\x0eupdateResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2X\n\rupdateService\x12G\n\x06update\x12\x1d.src.main.proto.updateRequest\x1a\x1e.src.main.proto.updateResponseb\x06proto3')



_UPDATEREQUEST = DESCRIPTOR.message_types_by_name['updateRequest']
_NODEINFO = DESCRIPTOR.message_types_by_name['nodeInfo']
_LINKINFO = DESCRIPTOR.message_types_by_name['linkInfo']
_NODEDESCRIPTORS = DESCRIPTOR.message_types_by_name['NodeDescriptors']
_UPDATERESPONSE = DESCRIPTOR.message_types_by_name['updateResponse']
updateRequest = _reflection.GeneratedProtocolMessageType('updateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'grpcService_pb2'
  # @@protoc_insertion_point(class_scope:src.main.proto.updateRequest)
  })
_sym_db.RegisterMessage(updateRequest)

nodeInfo = _reflection.GeneratedProtocolMessageType('nodeInfo', (_message.Message,), {
  'DESCRIPTOR' : _NODEINFO,
  '__module__' : 'grpcService_pb2'
  # @@protoc_insertion_point(class_scope:src.main.proto.nodeInfo)
  })
_sym_db.RegisterMessage(nodeInfo)

linkInfo = _reflection.GeneratedProtocolMessageType('linkInfo', (_message.Message,), {
  'DESCRIPTOR' : _LINKINFO,
  '__module__' : 'grpcService_pb2'
  # @@protoc_insertion_point(class_scope:src.main.proto.linkInfo)
  })
_sym_db.RegisterMessage(linkInfo)

NodeDescriptors = _reflection.GeneratedProtocolMessageType('NodeDescriptors', (_message.Message,), {
  'DESCRIPTOR' : _NODEDESCRIPTORS,
  '__module__' : 'grpcService_pb2'
  # @@protoc_insertion_point(class_scope:src.main.proto.NodeDescriptors)
  })
_sym_db.RegisterMessage(NodeDescriptors)

updateResponse = _reflection.GeneratedProtocolMessageType('updateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'grpcService_pb2'
  # @@protoc_insertion_point(class_scope:src.main.proto.updateResponse)
  })
_sym_db.RegisterMessage(updateResponse)

_UPDATESERVICE = DESCRIPTOR.services_by_name['updateService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPDATEREQUEST._serialized_start=38
  _UPDATEREQUEST._serialized_end=198
  _NODEINFO._serialized_start=200
  _NODEINFO._serialized_end=294
  _LINKINFO._serialized_start=297
  _LINKINFO._serialized_end=691
  _NODEDESCRIPTORS._serialized_start=693
  _NODEDESCRIPTORS._serialized_end=745
  _UPDATERESPONSE._serialized_start=747
  _UPDATERESPONSE._serialized_end=776
  _UPDATESERVICE._serialized_start=778
  _UPDATESERVICE._serialized_end=866
# @@protoc_insertion_point(module_scope)
