# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import grpcService_pb2 as grpcService__pb2


class updateServiceStub(object):
    """Defining a Service, a Service can have multiple RPC operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.update = channel.unary_unary(
                '/src.main.proto.updateService/update',
                request_serializer=grpcService__pb2.updateRequest.SerializeToString,
                response_deserializer=grpcService__pb2.updateResponse.FromString,
                )


class updateServiceServicer(object):
    """Defining a Service, a Service can have multiple RPC operations
    """

    def update(self, request, context):
        """MODIFY HERE: Update the return to streaming return.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_updateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=grpcService__pb2.updateRequest.FromString,
                    response_serializer=grpcService__pb2.updateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'src.main.proto.updateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class updateService(object):
    """Defining a Service, a Service can have multiple RPC operations
    """

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/src.main.proto.updateService/update',
            grpcService__pb2.updateRequest.SerializeToString,
            grpcService__pb2.updateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
