apiVersion: v1
kind: Namespace
metadata:
  name: scenario
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: h1-ingress-net
  namespace: scenario
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br-h1-i",
    "ipam": {
      "type": "static",
      "addresses": []
    }
  }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ingress-middle1-net
  namespace: scenario
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br-i-m1",
    "ipam": {
      "type": "static",
      "addresses": []
    }
  }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: middle2-egress-net
  namespace: scenario
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br-m2-e",
    "ipam": {
      "type": "static",
      "addresses": []
    }
  }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: egress-h2-net
  namespace: scenario
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br-e-h2",
    "ipam": {
      "type": "static",
      "addresses": []
    }
  }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: controller-net
  namespace: scenario
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br-ctrl",
    "ipam": {
      "type": "static",
      "addresses": []
    }
  }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: kafka-net
  namespace: scenario
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br-kafka",
    "ipam": {
      "type": "static",
      "subnet": "10.2.1.0/24",
      "rangeStart": "10.2.1.3",
      "rangeEnd": "10.2.1.254",
      "gateway": "10.2.1.1",
      "routes": [{"dst": "0.0.0.0/0"}]
    }
  }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: middle1-pod1
  namespace: scenario
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "m1-p1",
    "ipam": {
      "type": "static",
      "addresses": []
    }
  }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: pod1-pod2
  namespace: scenario
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "p1-p2",
    "ipam": {
      "type": "static",
      "addresses": []
    }
  }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: pod2-m2
  namespace: scenario
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "p2-m2",
    "ipam": {
      "type": "static",
      "addresses": []
    }
  }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cluster-network
  namespace: scenario
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eno8303",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": []
    }
  }'

