# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_connectivity_getconnectionendpointdetails_input import TapiConnectivityGetconnectionendpointdetailsInput  # noqa: F401,E501
from tapi_server import util


class OperationsTapiconnectivitygetconnectionendpointdetailsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input: TapiConnectivityGetconnectionendpointdetailsInput=None):  # noqa: E501
        """OperationsTapiconnectivitygetconnectionendpointdetailsBody - a model defined in Swagger

        :param input: The input of this OperationsTapiconnectivitygetconnectionendpointdetailsBody.  # noqa: E501
        :type input: TapiConnectivityGetconnectionendpointdetailsInput
        """
        self.swagger_types = {
            'input': TapiConnectivityGetconnectionendpointdetailsInput
        }

        self.attribute_map = {
            'input': 'input'
        }
        self._input = input

    @classmethod
    def from_dict(cls, dikt) -> 'OperationsTapiconnectivitygetconnectionendpointdetailsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The operations_tapiconnectivitygetconnectionendpointdetails_body of this OperationsTapiconnectivitygetconnectionendpointdetailsBody.  # noqa: E501
        :rtype: OperationsTapiconnectivitygetconnectionendpointdetailsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input(self) -> TapiConnectivityGetconnectionendpointdetailsInput:
        """Gets the input of this OperationsTapiconnectivitygetconnectionendpointdetailsBody.


        :return: The input of this OperationsTapiconnectivitygetconnectionendpointdetailsBody.
        :rtype: TapiConnectivityGetconnectionendpointdetailsInput
        """
        return self._input

    @input.setter
    def input(self, input: TapiConnectivityGetconnectionendpointdetailsInput):
        """Sets the input of this OperationsTapiconnectivitygetconnectionendpointdetailsBody.


        :param input: The input of this OperationsTapiconnectivitygetconnectionendpointdetailsBody.
        :type input: TapiConnectivityGetconnectionendpointdetailsInput
        """

        self._input = input
