# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_notification_updatenotificationsubscriptionservice_input import TapiNotificationUpdatenotificationsubscriptionserviceInput  # noqa: F401,E501
from tapi_server import util


class OperationsTapinotificationupdatenotificationsubscriptionserviceBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input: TapiNotificationUpdatenotificationsubscriptionserviceInput=None):  # noqa: E501
        """OperationsTapinotificationupdatenotificationsubscriptionserviceBody - a model defined in Swagger

        :param input: The input of this OperationsTapinotificationupdatenotificationsubscriptionserviceBody.  # noqa: E501
        :type input: TapiNotificationUpdatenotificationsubscriptionserviceInput
        """
        self.swagger_types = {
            'input': TapiNotificationUpdatenotificationsubscriptionserviceInput
        }

        self.attribute_map = {
            'input': 'input'
        }
        self._input = input

    @classmethod
    def from_dict(cls, dikt) -> 'OperationsTapinotificationupdatenotificationsubscriptionserviceBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The operations_tapinotificationupdatenotificationsubscriptionservice_body of this OperationsTapinotificationupdatenotificationsubscriptionserviceBody.  # noqa: E501
        :rtype: OperationsTapinotificationupdatenotificationsubscriptionserviceBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input(self) -> TapiNotificationUpdatenotificationsubscriptionserviceInput:
        """Gets the input of this OperationsTapinotificationupdatenotificationsubscriptionserviceBody.


        :return: The input of this OperationsTapinotificationupdatenotificationsubscriptionserviceBody.
        :rtype: TapiNotificationUpdatenotificationsubscriptionserviceInput
        """
        return self._input

    @input.setter
    def input(self, input: TapiNotificationUpdatenotificationsubscriptionserviceInput):
        """Sets the input of this OperationsTapinotificationupdatenotificationsubscriptionserviceBody.


        :param input: The input of this OperationsTapinotificationupdatenotificationsubscriptionserviceBody.
        :type input: TapiNotificationUpdatenotificationsubscriptionserviceInput
        """

        self._input = input
