# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_notification_getnotificationsubscriptionservicedetails_input import TapiNotificationGetnotificationsubscriptionservicedetailsInput  # noqa: F401,E501
from tapi_server import util


class OperationsTapinotificationgetnotificationsubscriptionservicedetailsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input: TapiNotificationGetnotificationsubscriptionservicedetailsInput=None):  # noqa: E501
        """OperationsTapinotificationgetnotificationsubscriptionservicedetailsBody - a model defined in Swagger

        :param input: The input of this OperationsTapinotificationgetnotificationsubscriptionservicedetailsBody.  # noqa: E501
        :type input: TapiNotificationGetnotificationsubscriptionservicedetailsInput
        """
        self.swagger_types = {
            'input': TapiNotificationGetnotificationsubscriptionservicedetailsInput
        }

        self.attribute_map = {
            'input': 'input'
        }
        self._input = input

    @classmethod
    def from_dict(cls, dikt) -> 'OperationsTapinotificationgetnotificationsubscriptionservicedetailsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The operations_tapinotificationgetnotificationsubscriptionservicedetails_body of this OperationsTapinotificationgetnotificationsubscriptionservicedetailsBody.  # noqa: E501
        :rtype: OperationsTapinotificationgetnotificationsubscriptionservicedetailsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input(self) -> TapiNotificationGetnotificationsubscriptionservicedetailsInput:
        """Gets the input of this OperationsTapinotificationgetnotificationsubscriptionservicedetailsBody.


        :return: The input of this OperationsTapinotificationgetnotificationsubscriptionservicedetailsBody.
        :rtype: TapiNotificationGetnotificationsubscriptionservicedetailsInput
        """
        return self._input

    @input.setter
    def input(self, input: TapiNotificationGetnotificationsubscriptionservicedetailsInput):
        """Sets the input of this OperationsTapinotificationgetnotificationsubscriptionservicedetailsBody.


        :param input: The input of this OperationsTapinotificationgetnotificationsubscriptionservicedetailsBody.
        :type input: TapiNotificationGetnotificationsubscriptionservicedetailsInput
        """

        self._input = input
