# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_path_computation_optimizep2ppath_input import TapiPathComputationOptimizep2ppathInput  # noqa: F401,E501
from tapi_server import util


class OperationsTapipathcomputationoptimizep2ppathBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input: TapiPathComputationOptimizep2ppathInput=None):  # noqa: E501
        """OperationsTapipathcomputationoptimizep2ppathBody - a model defined in Swagger

        :param input: The input of this OperationsTapipathcomputationoptimizep2ppathBody.  # noqa: E501
        :type input: TapiPathComputationOptimizep2ppathInput
        """
        self.swagger_types = {
            'input': TapiPathComputationOptimizep2ppathInput
        }

        self.attribute_map = {
            'input': 'input'
        }
        self._input = input

    @classmethod
    def from_dict(cls, dikt) -> 'OperationsTapipathcomputationoptimizep2ppathBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The operations_tapipathcomputationoptimizep2ppath_body of this OperationsTapipathcomputationoptimizep2ppathBody.  # noqa: E501
        :rtype: OperationsTapipathcomputationoptimizep2ppathBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input(self) -> TapiPathComputationOptimizep2ppathInput:
        """Gets the input of this OperationsTapipathcomputationoptimizep2ppathBody.


        :return: The input of this OperationsTapipathcomputationoptimizep2ppathBody.
        :rtype: TapiPathComputationOptimizep2ppathInput
        """
        return self._input

    @input.setter
    def input(self, input: TapiPathComputationOptimizep2ppathInput):
        """Sets the input of this OperationsTapipathcomputationoptimizep2ppathBody.


        :param input: The input of this OperationsTapipathcomputationoptimizep2ppathBody.
        :type input: TapiPathComputationOptimizep2ppathInput
        """

        self._input = input
