# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_notification_createnotificationsubscriptionservice_input import TapiNotificationCreatenotificationsubscriptionserviceInput  # noqa: F401,E501
from tapi_server import util


class OperationsTapinotificationcreatenotificationsubscriptionserviceBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input: TapiNotificationCreatenotificationsubscriptionserviceInput=None):  # noqa: E501
        """OperationsTapinotificationcreatenotificationsubscriptionserviceBody - a model defined in Swagger

        :param input: The input of this OperationsTapinotificationcreatenotificationsubscriptionserviceBody.  # noqa: E501
        :type input: TapiNotificationCreatenotificationsubscriptionserviceInput
        """
        self.swagger_types = {
            'input': TapiNotificationCreatenotificationsubscriptionserviceInput
        }

        self.attribute_map = {
            'input': 'input'
        }
        self._input = input

    @classmethod
    def from_dict(cls, dikt) -> 'OperationsTapinotificationcreatenotificationsubscriptionserviceBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The operations_tapinotificationcreatenotificationsubscriptionservice_body of this OperationsTapinotificationcreatenotificationsubscriptionserviceBody.  # noqa: E501
        :rtype: OperationsTapinotificationcreatenotificationsubscriptionserviceBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input(self) -> TapiNotificationCreatenotificationsubscriptionserviceInput:
        """Gets the input of this OperationsTapinotificationcreatenotificationsubscriptionserviceBody.


        :return: The input of this OperationsTapinotificationcreatenotificationsubscriptionserviceBody.
        :rtype: TapiNotificationCreatenotificationsubscriptionserviceInput
        """
        return self._input

    @input.setter
    def input(self, input: TapiNotificationCreatenotificationsubscriptionserviceInput):
        """Sets the input of this OperationsTapinotificationcreatenotificationsubscriptionserviceBody.


        :param input: The input of this OperationsTapinotificationcreatenotificationsubscriptionserviceBody.
        :type input: TapiNotificationCreatenotificationsubscriptionserviceInput
        """

        self._input = input
