# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_connectivity_getconnectiondetails_input import TapiConnectivityGetconnectiondetailsInput  # noqa: F401,E501
from tapi_server import util


class OperationsTapiconnectivitygetconnectiondetailsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input: TapiConnectivityGetconnectiondetailsInput=None):  # noqa: E501
        """OperationsTapiconnectivitygetconnectiondetailsBody - a model defined in Swagger

        :param input: The input of this OperationsTapiconnectivitygetconnectiondetailsBody.  # noqa: E501
        :type input: TapiConnectivityGetconnectiondetailsInput
        """
        self.swagger_types = {
            'input': TapiConnectivityGetconnectiondetailsInput
        }

        self.attribute_map = {
            'input': 'input'
        }
        self._input = input

    @classmethod
    def from_dict(cls, dikt) -> 'OperationsTapiconnectivitygetconnectiondetailsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The operations_tapiconnectivitygetconnectiondetails_body of this OperationsTapiconnectivitygetconnectiondetailsBody.  # noqa: E501
        :rtype: OperationsTapiconnectivitygetconnectiondetailsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input(self) -> TapiConnectivityGetconnectiondetailsInput:
        """Gets the input of this OperationsTapiconnectivitygetconnectiondetailsBody.


        :return: The input of this OperationsTapiconnectivitygetconnectiondetailsBody.
        :rtype: TapiConnectivityGetconnectiondetailsInput
        """
        return self._input

    @input.setter
    def input(self, input: TapiConnectivityGetconnectiondetailsInput):
        """Sets the input of this OperationsTapiconnectivitygetconnectiondetailsBody.


        :param input: The input of this OperationsTapiconnectivitygetconnectiondetailsBody.
        :type input: TapiConnectivityGetconnectiondetailsInput
        """

        self._input = input
