# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_topology_node import TapiTopologyTopologyNode  # noqa: F401,E501
from tapi_server import util


class TapiTopologyTopologyNodeWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, node: TapiTopologyTopologyNode=None):  # noqa: E501
        """TapiTopologyTopologyNodeWrapper - a model defined in Swagger

        :param node: The node of this TapiTopologyTopologyNodeWrapper.  # noqa: E501
        :type node: TapiTopologyTopologyNode
        """
        self.swagger_types = {
            'node': TapiTopologyTopologyNode
        }

        self.attribute_map = {
            'node': 'node'
        }
        self._node = node

    @classmethod
    def from_dict(cls, dikt) -> 'TapiTopologyTopologyNodeWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.topology.topology.NodeWrapper of this TapiTopologyTopologyNodeWrapper.  # noqa: E501
        :rtype: TapiTopologyTopologyNodeWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node(self) -> TapiTopologyTopologyNode:
        """Gets the node of this TapiTopologyTopologyNodeWrapper.


        :return: The node of this TapiTopologyTopologyNodeWrapper.
        :rtype: TapiTopologyTopologyNode
        """
        return self._node

    @node.setter
    def node(self, node: TapiTopologyTopologyNode):
        """Sets the node of this TapiTopologyTopologyNodeWrapper.


        :param node: The node of this TapiTopologyTopologyNodeWrapper.
        :type node: TapiTopologyTopologyNode
        """

        self._node = node
