# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_connectivity_connectivity_service import TapiConnectivityConnectivityService  # noqa: F401,E501
from tapi_server import util


class TapiConnectivityUpdateconnectivityserviceOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service: TapiConnectivityConnectivityService=None):  # noqa: E501
        """TapiConnectivityUpdateconnectivityserviceOutput - a model defined in Swagger

        :param service: The service of this TapiConnectivityUpdateconnectivityserviceOutput.  # noqa: E501
        :type service: TapiConnectivityConnectivityService
        """
        self.swagger_types = {
            'service': TapiConnectivityConnectivityService
        }

        self.attribute_map = {
            'service': 'service'
        }
        self._service = service

    @classmethod
    def from_dict(cls, dikt) -> 'TapiConnectivityUpdateconnectivityserviceOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.connectivity.updateconnectivityservice.Output of this TapiConnectivityUpdateconnectivityserviceOutput.  # noqa: E501
        :rtype: TapiConnectivityUpdateconnectivityserviceOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service(self) -> TapiConnectivityConnectivityService:
        """Gets the service of this TapiConnectivityUpdateconnectivityserviceOutput.


        :return: The service of this TapiConnectivityUpdateconnectivityserviceOutput.
        :rtype: TapiConnectivityConnectivityService
        """
        return self._service

    @service.setter
    def service(self, service: TapiConnectivityConnectivityService):
        """Sets the service of this TapiConnectivityUpdateconnectivityserviceOutput.


        :param service: The service of this TapiConnectivityUpdateconnectivityserviceOutput.
        :type service: TapiConnectivityConnectivityService
        """

        self._service = service
