# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_link import TapiTopologyLink  # noqa: F401,E501
from tapi_server import util


class TapiTopologyLinkWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, link: TapiTopologyLink=None):  # noqa: E501
        """TapiTopologyLinkWrapper - a model defined in Swagger

        :param link: The link of this TapiTopologyLinkWrapper.  # noqa: E501
        :type link: TapiTopologyLink
        """
        self.swagger_types = {
            'link': TapiTopologyLink
        }

        self.attribute_map = {
            'link': 'link'
        }
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'TapiTopologyLinkWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.topology.LinkWrapper of this TapiTopologyLinkWrapper.  # noqa: E501
        :rtype: TapiTopologyLinkWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> TapiTopologyLink:
        """Gets the link of this TapiTopologyLinkWrapper.


        :return: The link of this TapiTopologyLinkWrapper.
        :rtype: TapiTopologyLink
        """
        return self._link

    @link.setter
    def link(self, link: TapiTopologyLink):
        """Sets the link of this TapiTopologyLinkWrapper.


        :param link: The link of this TapiTopologyLinkWrapper.
        :type link: TapiTopologyLink
        """

        self._link = link
