# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_resilience_type import TapiTopologyResilienceType  # noqa: F401,E501
from tapi_server import util


class TapiTopologyResilienceTypeWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, resilience_type: TapiTopologyResilienceType=None):  # noqa: E501
        """TapiTopologyResilienceTypeWrapper - a model defined in Swagger

        :param resilience_type: The resilience_type of this TapiTopologyResilienceTypeWrapper.  # noqa: E501
        :type resilience_type: TapiTopologyResilienceType
        """
        self.swagger_types = {
            'resilience_type': TapiTopologyResilienceType
        }

        self.attribute_map = {
            'resilience_type': 'resilience-type'
        }
        self._resilience_type = resilience_type

    @classmethod
    def from_dict(cls, dikt) -> 'TapiTopologyResilienceTypeWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.topology.ResilienceTypeWrapper of this TapiTopologyResilienceTypeWrapper.  # noqa: E501
        :rtype: TapiTopologyResilienceTypeWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resilience_type(self) -> TapiTopologyResilienceType:
        """Gets the resilience_type of this TapiTopologyResilienceTypeWrapper.


        :return: The resilience_type of this TapiTopologyResilienceTypeWrapper.
        :rtype: TapiTopologyResilienceType
        """
        return self._resilience_type

    @resilience_type.setter
    def resilience_type(self, resilience_type: TapiTopologyResilienceType):
        """Sets the resilience_type of this TapiTopologyResilienceTypeWrapper.


        :param resilience_type: The resilience_type of this TapiTopologyResilienceTypeWrapper.
        :type resilience_type: TapiTopologyResilienceType
        """

        self._resilience_type = resilience_type
