# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_validation_mechanism import TapiTopologyValidationMechanism  # noqa: F401,E501
from tapi_server import util


class TapiTopologyValidationMechanismWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, validation_mechanism: TapiTopologyValidationMechanism=None):  # noqa: E501
        """TapiTopologyValidationMechanismWrapper - a model defined in Swagger

        :param validation_mechanism: The validation_mechanism of this TapiTopologyValidationMechanismWrapper.  # noqa: E501
        :type validation_mechanism: TapiTopologyValidationMechanism
        """
        self.swagger_types = {
            'validation_mechanism': TapiTopologyValidationMechanism
        }

        self.attribute_map = {
            'validation_mechanism': 'validation-mechanism'
        }
        self._validation_mechanism = validation_mechanism

    @classmethod
    def from_dict(cls, dikt) -> 'TapiTopologyValidationMechanismWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.topology.ValidationMechanismWrapper of this TapiTopologyValidationMechanismWrapper.  # noqa: E501
        :rtype: TapiTopologyValidationMechanismWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def validation_mechanism(self) -> TapiTopologyValidationMechanism:
        """Gets the validation_mechanism of this TapiTopologyValidationMechanismWrapper.


        :return: The validation_mechanism of this TapiTopologyValidationMechanismWrapper.
        :rtype: TapiTopologyValidationMechanism
        """
        return self._validation_mechanism

    @validation_mechanism.setter
    def validation_mechanism(self, validation_mechanism: TapiTopologyValidationMechanism):
        """Sets the validation_mechanism of this TapiTopologyValidationMechanismWrapper.


        :param validation_mechanism: The validation_mechanism of this TapiTopologyValidationMechanismWrapper.
        :type validation_mechanism: TapiTopologyValidationMechanism
        """

        self._validation_mechanism = validation_mechanism
