# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_connectivity_connection_end_point_ref import TapiConnectivityConnectionEndPointRef  # noqa: F401,E501
from tapi_server import util


class TapiConnectivityConnectionEndPointRefWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, connection_end_point: TapiConnectivityConnectionEndPointRef=None):  # noqa: E501
        """TapiConnectivityConnectionEndPointRefWrapper - a model defined in Swagger

        :param connection_end_point: The connection_end_point of this TapiConnectivityConnectionEndPointRefWrapper.  # noqa: E501
        :type connection_end_point: TapiConnectivityConnectionEndPointRef
        """
        self.swagger_types = {
            'connection_end_point': TapiConnectivityConnectionEndPointRef
        }

        self.attribute_map = {
            'connection_end_point': 'connection-end-point'
        }
        self._connection_end_point = connection_end_point

    @classmethod
    def from_dict(cls, dikt) -> 'TapiConnectivityConnectionEndPointRefWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.connectivity.ConnectionEndPointRefWrapper of this TapiConnectivityConnectionEndPointRefWrapper.  # noqa: E501
        :rtype: TapiConnectivityConnectionEndPointRefWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def connection_end_point(self) -> TapiConnectivityConnectionEndPointRef:
        """Gets the connection_end_point of this TapiConnectivityConnectionEndPointRefWrapper.


        :return: The connection_end_point of this TapiConnectivityConnectionEndPointRefWrapper.
        :rtype: TapiConnectivityConnectionEndPointRef
        """
        return self._connection_end_point

    @connection_end_point.setter
    def connection_end_point(self, connection_end_point: TapiConnectivityConnectionEndPointRef):
        """Sets the connection_end_point of this TapiConnectivityConnectionEndPointRefWrapper.


        :param connection_end_point: The connection_end_point of this TapiConnectivityConnectionEndPointRefWrapper.
        :type connection_end_point: TapiConnectivityConnectionEndPointRef
        """

        self._connection_end_point = connection_end_point
