# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_connectivity_connection_end_point import TapiConnectivityConnectionEndPoint  # noqa: F401,E501
from tapi_server import util


class TapiConnectivityCepList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, connection_end_point: List[TapiConnectivityConnectionEndPoint]=None):  # noqa: E501
        """TapiConnectivityCepList - a model defined in Swagger

        :param connection_end_point: The connection_end_point of this TapiConnectivityCepList.  # noqa: E501
        :type connection_end_point: List[TapiConnectivityConnectionEndPoint]
        """
        self.swagger_types = {
            'connection_end_point': List[TapiConnectivityConnectionEndPoint]
        }

        self.attribute_map = {
            'connection_end_point': 'connection-end-point'
        }
        self._connection_end_point = connection_end_point

    @classmethod
    def from_dict(cls, dikt) -> 'TapiConnectivityCepList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.connectivity.CepList of this TapiConnectivityCepList.  # noqa: E501
        :rtype: TapiConnectivityCepList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def connection_end_point(self) -> List[TapiConnectivityConnectionEndPoint]:
        """Gets the connection_end_point of this TapiConnectivityCepList.

        none  # noqa: E501

        :return: The connection_end_point of this TapiConnectivityCepList.
        :rtype: List[TapiConnectivityConnectionEndPoint]
        """
        return self._connection_end_point

    @connection_end_point.setter
    def connection_end_point(self, connection_end_point: List[TapiConnectivityConnectionEndPoint]):
        """Sets the connection_end_point of this TapiConnectivityCepList.

        none  # noqa: E501

        :param connection_end_point: The connection_end_point of this TapiConnectivityCepList.
        :type connection_end_point: List[TapiConnectivityConnectionEndPoint]
        """

        self._connection_end_point = connection_end_point
