# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_node_edge_point_ref import TapiTopologyNodeEdgePointRef  # noqa: F401,E501
from tapi_server import util


class TapiConnectivityConnectionEndPointRef(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, node_edge_point_uuid: str=None, connection_end_point_uuid: str=None):  # noqa: E501
        """TapiConnectivityConnectionEndPointRef - a model defined in Swagger

        :param node_edge_point_uuid: The node_edge_point_uuid of this TapiConnectivityConnectionEndPointRef.  # noqa: E501
        :type node_edge_point_uuid: str
        :param connection_end_point_uuid: The connection_end_point_uuid of this TapiConnectivityConnectionEndPointRef.  # noqa: E501
        :type connection_end_point_uuid: str
        """
        self.swagger_types = {
            'node_edge_point_uuid': str,
            'connection_end_point_uuid': str
        }

        self.attribute_map = {
            'node_edge_point_uuid': 'node-edge-point-uuid',
            'connection_end_point_uuid': 'connection-end-point-uuid'
        }
        self._node_edge_point_uuid = node_edge_point_uuid
        self._connection_end_point_uuid = connection_end_point_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'TapiConnectivityConnectionEndPointRef':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.connectivity.ConnectionEndPointRef of this TapiConnectivityConnectionEndPointRef.  # noqa: E501
        :rtype: TapiConnectivityConnectionEndPointRef
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node_edge_point_uuid(self) -> str:
        """Gets the node_edge_point_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :return: The node_edge_point_uuid of this TapiConnectivityConnectionEndPointRef.
        :rtype: str
        """
        return self._node_edge_point_uuid

    @node_edge_point_uuid.setter
    def node_edge_point_uuid(self, node_edge_point_uuid: str):
        """Sets the node_edge_point_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :param node_edge_point_uuid: The node_edge_point_uuid of this TapiConnectivityConnectionEndPointRef.
        :type node_edge_point_uuid: str
        """

        self._node_edge_point_uuid = node_edge_point_uuid

    @property
    def connection_end_point_uuid(self) -> str:
        """Gets the connection_end_point_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :return: The connection_end_point_uuid of this TapiConnectivityConnectionEndPointRef.
        :rtype: str
        """
        return self._connection_end_point_uuid

    @connection_end_point_uuid.setter
    def connection_end_point_uuid(self, connection_end_point_uuid: str):
        """Sets the connection_end_point_uuid of this TapiConnectivityConnectionEndPointRef.

        none  # noqa: E501

        :param connection_end_point_uuid: The connection_end_point_uuid of this TapiConnectivityConnectionEndPointRef.
        :type connection_end_point_uuid: str
        """

        self._connection_end_point_uuid = connection_end_point_uuid
