# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_topology_inter_rule_group import TapiTopologyInterRuleGroup  # noqa: F401,E501
from tapi_server import util


class TapiTopologyInterRuleGroupWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, inter_rule_group: TapiTopologyInterRuleGroup=None):  # noqa: E501
        """TapiTopologyInterRuleGroupWrapper - a model defined in Swagger

        :param inter_rule_group: The inter_rule_group of this TapiTopologyInterRuleGroupWrapper.  # noqa: E501
        :type inter_rule_group: TapiTopologyInterRuleGroup
        """
        self.swagger_types = {
            'inter_rule_group': TapiTopologyInterRuleGroup
        }

        self.attribute_map = {
            'inter_rule_group': 'inter-rule-group'
        }
        self._inter_rule_group = inter_rule_group

    @classmethod
    def from_dict(cls, dikt) -> 'TapiTopologyInterRuleGroupWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.topology.InterRuleGroupWrapper of this TapiTopologyInterRuleGroupWrapper.  # noqa: E501
        :rtype: TapiTopologyInterRuleGroupWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def inter_rule_group(self) -> TapiTopologyInterRuleGroup:
        """Gets the inter_rule_group of this TapiTopologyInterRuleGroupWrapper.


        :return: The inter_rule_group of this TapiTopologyInterRuleGroupWrapper.
        :rtype: TapiTopologyInterRuleGroup
        """
        return self._inter_rule_group

    @inter_rule_group.setter
    def inter_rule_group(self, inter_rule_group: TapiTopologyInterRuleGroup):
        """Sets the inter_rule_group of this TapiTopologyInterRuleGroupWrapper.


        :param inter_rule_group: The inter_rule_group of this TapiTopologyInterRuleGroupWrapper.
        :type inter_rule_group: TapiTopologyInterRuleGroup
        """

        self._inter_rule_group = inter_rule_group
