# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_path_computation_path_ref import TapiPathComputationPathRef  # noqa: F401,E501
from tapi_server import util


class TapiPathComputationPathRefWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, path: TapiPathComputationPathRef=None):  # noqa: E501
        """TapiPathComputationPathRefWrapper - a model defined in Swagger

        :param path: The path of this TapiPathComputationPathRefWrapper.  # noqa: E501
        :type path: TapiPathComputationPathRef
        """
        self.swagger_types = {
            'path': TapiPathComputationPathRef
        }

        self.attribute_map = {
            'path': 'path'
        }
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'TapiPathComputationPathRefWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.path.computation.PathRefWrapper of this TapiPathComputationPathRefWrapper.  # noqa: E501
        :rtype: TapiPathComputationPathRefWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self) -> TapiPathComputationPathRef:
        """Gets the path of this TapiPathComputationPathRefWrapper.


        :return: The path of this TapiPathComputationPathRefWrapper.
        :rtype: TapiPathComputationPathRef
        """
        return self._path

    @path.setter
    def path(self, path: TapiPathComputationPathRef):
        """Sets the path of this TapiPathComputationPathRefWrapper.


        :param path: The path of this TapiPathComputationPathRefWrapper.
        :type path: TapiPathComputationPathRef
        """

        self._path = path
