# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tapi_server.models.base_model_ import Model
from tapi_server.models.tapi_notification_notification_channel import TapiNotificationNotificationChannel  # noqa: F401,E501
from tapi_server import util


class TapiNotificationNotificationChannelWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, notification_channel: TapiNotificationNotificationChannel=None):  # noqa: E501
        """TapiNotificationNotificationChannelWrapper - a model defined in Swagger

        :param notification_channel: The notification_channel of this TapiNotificationNotificationChannelWrapper.  # noqa: E501
        :type notification_channel: TapiNotificationNotificationChannel
        """
        self.swagger_types = {
            'notification_channel': TapiNotificationNotificationChannel
        }

        self.attribute_map = {
            'notification_channel': 'notification-channel'
        }
        self._notification_channel = notification_channel

    @classmethod
    def from_dict(cls, dikt) -> 'TapiNotificationNotificationChannelWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tapi.notification.NotificationChannelWrapper of this TapiNotificationNotificationChannelWrapper.  # noqa: E501
        :rtype: TapiNotificationNotificationChannelWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_channel(self) -> TapiNotificationNotificationChannel:
        """Gets the notification_channel of this TapiNotificationNotificationChannelWrapper.


        :return: The notification_channel of this TapiNotificationNotificationChannelWrapper.
        :rtype: TapiNotificationNotificationChannel
        """
        return self._notification_channel

    @notification_channel.setter
    def notification_channel(self, notification_channel: TapiNotificationNotificationChannel):
        """Sets the notification_channel of this TapiNotificationNotificationChannelWrapper.


        :param notification_channel: The notification_channel of this TapiNotificationNotificationChannelWrapper.
        :type notification_channel: TapiNotificationNotificationChannel
        """

        self._notification_channel = notification_channel
