apiVersion: v1
kind: Pod
metadata:
  name: middlenode1
  namespace: scenario
  labels:
    app: middlenode1
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "middle1-middle2-net",
          "interface": "net2",
          "ips": [ "10.0.2.3/24" ],
          "mac": "02:42:0a:00:02:03"
        },
        {
          "name": "cluster-controller",
          "interface": "net3",
          "ips": [ "10.0.0.12/24" ],
          "mac": "02:42:0a:00:00:0c"
        },
        {
          "name": "cluster-network",
          "interface": "net1",
          "ips": [ "10.0.1.2/24" ],
          "mac": "02:42:0a:00:01:02"
        }
      ]
spec:
  dnsConfig:
    nameservers:
      - 8.8.8.8
  containers:
  - name: middlenode1
    image: jorgealmansa/p4-imagen:final
    securityContext:
      privileged: true
    command:
      - /bin/sh
      - -c
      - |
        apt update && apt install -y iptables
        echo 1 > /proc/sys/net/ipv4/ip_forward
        chmod +x /home/p4/pot/docker/run.sh
        /home/p4/pot/docker/run.sh 12
    volumeMounts:
    - mountPath: /home/p4/pot
      name: pot-volume
    - mountPath: /home/p4/pot/docker/run.sh
      name: pot-run-config
      subPath: run.sh
  volumes:
  - name: pot-volume
    hostPath:
      path: /home/mw/PoT/PoT_PRIVATEER
      type: Directory
  - name: pot-run-config
    configMap:
      name: pot-run-config
      defaultMode: 0755
---
apiVersion: v1
kind: Pod
metadata:
  name: middlenode2
  namespace: scenario
  labels:
    app: middlenode2
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "middle1-middle2-net",
          "interface": "net1",
          "ips": [ "10.0.2.2/24" ],
          "mac": "02:42:0a:00:02:02"
        },
        {
          "name": "cluster-controller",
          "interface": "net3",
          "ips": [ "10.0.0.13/24" ],
          "mac": "02:42:0a:00:00:0d"
        },
        {
          "name": "cluster-network",
          "interface": "net2",
          "ips": [ "10.0.3.3/24" ],
          "mac": "02:42:0a:00:03:03"
        }
      ]
spec:
  dnsConfig:
    nameservers:
      - 8.8.8.8
  containers:
  - name: middlenode2
    image: jorgealmansa/p4-imagen:final
    securityContext:
      privileged: true
    command:
      - /bin/sh
      - -c
      - |
        apt update && apt install -y iptables
        echo 1 > /proc/sys/net/ipv4/ip_forward
        chmod +x /home/p4/pot/docker/run.sh
        /home/p4/pot/docker/run.sh 13
    volumeMounts:
    - mountPath: /home/p4/pot
      name: pot-volume
    - mountPath: /home/p4/pot/docker/run.sh
      name: pot-run-config
      subPath: run.sh
  volumes:
  - name: pot-volume
    hostPath:
      path: /home/mw/PoT/PoT_PRIVATEER
      type: Directory
  - name: pot-run-config
    configMap:
      name: pot-run-config
      defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: middlenode1-service
  namespace: scenario
spec:
  type: ClusterIP
  selector:
    app: middlenode1
  ports:
    - name: grpc
      protocol: TCP
      port: 50002
      targetPort: 50002
  externalIPs:
    - 192.168.159.59  # IP del nodo físico o una IP estática accesible desde fuera
---
apiVersion: v1
kind: Service
metadata:
  name: middlenode2-service
  namespace: scenario
spec:
  type: ClusterIP
  selector:
    app: middlenode2
  ports:
    - name: grpc
      protocol: TCP
      port: 50003
      targetPort: 50003
  externalIPs:
    - 192.168.159.59  # IP del nodo físico o una IP estática accesible desde fuera
